---

- name: Creates directory
  file:
    path: ~/web
    state: directory

- name: Copy backend artifact
  template:
    src: ../../../../artifact.tar.gz
    dest: ~/web/artifact.tar.gz
# TODO write the tar.gz right into the files folder
- name: Installing backend
  shell: cd ~/web/ && tar -xf artifact.tar.gz && npm install

- name: Executing node
  shell: cd ~/web/ && pm2 stop default && pm2 start npm -- start
