---

- name: Creates directory
  file:
    path: ~/web
    state: directory

- name: Copy index test page
  template:
    src: "../../../../artifact.tar.gz"
    dest: "artifact.tar.gz"

- name: Installing backend
  shell: |
    tar -xf artifact.tar.gz
    npm install

- name: Executing node
  shell: |
    pm2 stop default
    pm2 start npm -- start
